### ISSUE TITLE
Update FalconLibrary License

### ISSUE THREAD

**Issue by prateekma** [FRCTeam4069/SaturnLibrary#6]
The MPL license requires modified files from a source project to also have the appropriate license header. Since a majority of this project is code directly from FalconLibrary, please update the code to comply with the license.

**Comment by Redrield** [comment]
The code in this library is from a diff of falcon library that was licensed under MIT. I have confirmed to the terms of that license. If I take code from falcon library in the future, I will conform to the terms of the new license.
